/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ged;

import java.io.IOException;
import javax.swing.table.DefaultTableModel;
import javax.swing.SwingConstants;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Comp
 */
public class GED_App extends javax.swing.JFrame
{
    private final int PROJECT_COLUMN = 0;
    private final int DESCRIPTION_COLUMN = 1;
    
    
    ProjectManager project_mgr;
    ConfigurationManager config_mgr;
    DiagramDialog diagram_dlg;

    /**
     * Creates new form GED_App
   * @throws java.io.IOException
     */
    public GED_App() throws IOException
    {
      project_mgr = ProjectManager.getInstance();
      config_mgr = ConfigurationManager.getInstance();
      initComponents();
      NewProjectDlg.setVisible(false);
      ConfirmDeleteProjectDlg.setVisible(false);
      NewDiagramDlg.setVisible(false);
      DiagramSelectDialog.setVisible(false);
      
      // Delete diagram is not a requirement, hide the button for it
      DeleteDiagramBtn.setVisible(false);
      
      diagram_dlg = new DiagramDialog(this, true);
    }
    
    public static GED_App ged;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    WorkspaceChooser = new javax.swing.JFileChooser();
    NewProjectDlg = new javax.swing.JDialog();
    NewProjOkBtn = new javax.swing.JButton();
    NewProjCancelBtn = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    NewProjNameText = new javax.swing.JTextField();
    NewProjDescText = new javax.swing.JTextField();
    ConfirmDeleteProjectDlg = new javax.swing.JDialog();
    ConfDeleteProjBtn = new javax.swing.JButton();
    ConfDeleteProjCancelBtn = new javax.swing.JButton();
    ConfirmDeleteProjMsg = new javax.swing.JLabel();
    DiagramSelectDialog = new javax.swing.JDialog();
    dialogScrollPane = new javax.swing.JScrollPane();
    ExistingDiagramsTable = new javax.swing.JTable();
    CreateDiagramBtn = new javax.swing.JButton();
    OpenDiagramBtn = new javax.swing.JButton();
    DeleteDiagramBtn = new javax.swing.JButton();
    ProjNameLabel = new javax.swing.JLabel();
    CloseProjectBtn = new javax.swing.JButton();
    NewDiagramDlg = new javax.swing.JDialog();
    NewDiagOkBtn = new javax.swing.JButton();
    NewDiagCancelBtn = new javax.swing.JButton();
    DiagNameLabel = new javax.swing.JLabel();
    NewDiagNameText = new javax.swing.JTextField();
    ConfirmDeleteDiagramDlg = new javax.swing.JDialog();
    ConfDeleteDiagBtn = new javax.swing.JButton();
    ConfDeleteDiagCancelBtn = new javax.swing.JButton();
    ConfirmDeleteDiagMsg = new javax.swing.JLabel();
    ProjectSelectDialog = new javax.swing.JPanel();
    CreateProjectBtn = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    ExistingProjectsTable = new javax.swing.JTable();
    OpenProjectBtn = new javax.swing.JButton();
    SelectWorkspaceBtn = new javax.swing.JButton();
    DeleteProjectBtn = new javax.swing.JButton();
    MainMenuBar = new javax.swing.JMenuBar();
    MainMenuFile = new javax.swing.JMenu();
    MainMenuExit = new javax.swing.JMenuItem();

    WorkspaceChooser.setCurrentDirectory(new java.io.File("C:\\"));
      WorkspaceChooser.setDialogTitle("Select Workspace Directory");
      WorkspaceChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

      NewProjectDlg.setMinimumSize(new java.awt.Dimension(400, 200));
      NewProjectDlg.setModal(true);

      NewProjOkBtn.setText("OK");
      NewProjOkBtn.addMouseListener(new java.awt.event.MouseAdapter()
      {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
          NewProjOkBtnMouseClicked(evt);
        }
      });

      NewProjCancelBtn.setText("Cancel");
      NewProjCancelBtn.addMouseListener(new java.awt.event.MouseAdapter()
      {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
          NewProjCancelBtnMouseClicked(evt);
        }
      });

      jLabel1.setText("Project Name:");

      jLabel2.setText("Project Description:");

      javax.swing.GroupLayout NewProjectDlgLayout = new javax.swing.GroupLayout(NewProjectDlg.getContentPane());
      NewProjectDlg.getContentPane().setLayout(NewProjectDlgLayout);
      NewProjectDlgLayout.setHorizontalGroup(
        NewProjectDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(NewProjectDlgLayout.createSequentialGroup()
          .addContainerGap()
          .addGroup(NewProjectDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewProjectDlgLayout.createSequentialGroup()
              .addGap(0, 262, Short.MAX_VALUE)
              .addComponent(NewProjCancelBtn)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(NewProjOkBtn))
            .addGroup(NewProjectDlgLayout.createSequentialGroup()
              .addComponent(jLabel2)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(NewProjDescText))
            .addGroup(NewProjectDlgLayout.createSequentialGroup()
              .addComponent(jLabel1)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(NewProjNameText)))
          .addContainerGap())
      );
      NewProjectDlgLayout.setVerticalGroup(
        NewProjectDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewProjectDlgLayout.createSequentialGroup()
          .addContainerGap()
          .addGroup(NewProjectDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel1)
            .addComponent(NewProjNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGap(18, 18, 18)
          .addGroup(NewProjectDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel2)
            .addComponent(NewProjDescText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addGroup(NewProjectDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(NewProjOkBtn)
            .addComponent(NewProjCancelBtn))
          .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      ConfirmDeleteProjectDlg.setMinimumSize(new java.awt.Dimension(400, 200));
      ConfirmDeleteProjectDlg.setModal(true);

      ConfDeleteProjBtn.setText("Delete");
      ConfDeleteProjBtn.addMouseListener(new java.awt.event.MouseAdapter()
      {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
          ConfDeleteProjBtnMouseClicked(evt);
        }
      });

      ConfDeleteProjCancelBtn.setText("Cancel");
      ConfDeleteProjCancelBtn.addMouseListener(new java.awt.event.MouseAdapter()
      {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
          ConfDeleteProjCancelBtnMouseClicked(evt);
        }
      });

      ConfirmDeleteProjMsg.setText("ARE YOU SURE YOU WANT TO DELETE PROJECT?");

      javax.swing.GroupLayout ConfirmDeleteProjectDlgLayout = new javax.swing.GroupLayout(ConfirmDeleteProjectDlg.getContentPane());
      ConfirmDeleteProjectDlg.getContentPane().setLayout(ConfirmDeleteProjectDlgLayout);
      ConfirmDeleteProjectDlgLayout.setHorizontalGroup(
        ConfirmDeleteProjectDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(ConfirmDeleteProjectDlgLayout.createSequentialGroup()
          .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(ConfDeleteProjBtn)
          .addGap(46, 46, 46)
          .addComponent(ConfDeleteProjCancelBtn)
          .addGap(131, 131, 131))
        .addGroup(ConfirmDeleteProjectDlgLayout.createSequentialGroup()
          .addGap(70, 70, 70)
          .addComponent(ConfirmDeleteProjMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGap(91, 91, 91))
      );
      ConfirmDeleteProjectDlgLayout.setVerticalGroup(
        ConfirmDeleteProjectDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConfirmDeleteProjectDlgLayout.createSequentialGroup()
          .addContainerGap()
          .addComponent(ConfirmDeleteProjMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addGroup(ConfirmDeleteProjectDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(ConfDeleteProjCancelBtn)
            .addComponent(ConfDeleteProjBtn))
          .addContainerGap())
      );

      DiagramSelectDialog.setModal(true);

      ExistingDiagramsTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][]
        {

        },
        new String []
        {
          "Diagram"
        }
      )
      {
        Class[] types = new Class []
        {
          java.lang.String.class
        };
        boolean[] canEdit = new boolean []
        {
          false
        };

        public Class getColumnClass(int columnIndex)
        {
          return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex)
        {
          return canEdit [columnIndex];
        }
      });
      ExistingDiagramsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
      dialogScrollPane.setViewportView(ExistingDiagramsTable);

      CreateDiagramBtn.setText("Create Diagram");
      CreateDiagramBtn.addMouseListener(new java.awt.event.MouseAdapter()
      {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
          CreateDiagramBtnMouseClicked(evt);
        }
      });

      OpenDiagramBtn.setText("Open Diagram");
      OpenDiagramBtn.addMouseListener(new java.awt.event.MouseAdapter()
      {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
          OpenDiagramBtnMouseClicked(evt);
        }
      });

      DeleteDiagramBtn.setText("Delete Diagram");
      DeleteDiagramBtn.addMouseListener(new java.awt.event.MouseAdapter()
      {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
          DeleteDiagramBtnMouseClicked(evt);
        }
      });

      ProjNameLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
      ProjNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      ProjNameLabel.setText("Project Name");

      CloseProjectBtn.setText("Close Project");
      CloseProjectBtn.addMouseListener(new java.awt.event.MouseAdapter()
      {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
          CloseProjectBtnMouseClicked(evt);
        }
      });

      javax.swing.GroupLayout DiagramSelectDialogLayout = new javax.swing.GroupLayout(DiagramSelectDialog.getContentPane());
      DiagramSelectDialog.getContentPane().setLayout(DiagramSelectDialogLayout);
      DiagramSelectDialogLayout.setHorizontalGroup(
        DiagramSelectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(DiagramSelectDialogLayout.createSequentialGroup()
          .addContainerGap()
          .addGroup(DiagramSelectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProjNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dialogScrollPane)
            .addGroup(DiagramSelectDialogLayout.createSequentialGroup()
              .addComponent(CreateDiagramBtn)
              .addGap(0, 379, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiagramSelectDialogLayout.createSequentialGroup()
              .addGap(0, 0, Short.MAX_VALUE)
              .addGroup(DiagramSelectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiagramSelectDialogLayout.createSequentialGroup()
                  .addComponent(DeleteDiagramBtn)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(OpenDiagramBtn))
                .addComponent(CloseProjectBtn, javax.swing.GroupLayout.Alignment.TRAILING))))
          .addContainerGap())
      );
      DiagramSelectDialogLayout.setVerticalGroup(
        DiagramSelectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiagramSelectDialogLayout.createSequentialGroup()
          .addContainerGap()
          .addComponent(ProjNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addComponent(CreateDiagramBtn)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addComponent(dialogScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addGroup(DiagramSelectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(OpenDiagramBtn)
            .addComponent(DeleteDiagramBtn))
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
          .addComponent(CloseProjectBtn)
          .addContainerGap())
      );

      NewDiagramDlg.setMinimumSize(new java.awt.Dimension(400, 200));
      NewDiagramDlg.setModal(true);

      NewDiagOkBtn.setText("OK");
      NewDiagOkBtn.addMouseListener(new java.awt.event.MouseAdapter()
      {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
          NewDiagOkBtnMouseClicked(evt);
        }
      });

      NewDiagCancelBtn.setText("Cancel");
      NewDiagCancelBtn.addMouseListener(new java.awt.event.MouseAdapter()
      {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
          NewDiagCancelBtnMouseClicked(evt);
        }
      });

      DiagNameLabel.setText("Diagram Name:");

      javax.swing.GroupLayout NewDiagramDlgLayout = new javax.swing.GroupLayout(NewDiagramDlg.getContentPane());
      NewDiagramDlg.getContentPane().setLayout(NewDiagramDlgLayout);
      NewDiagramDlgLayout.setHorizontalGroup(
        NewDiagramDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(NewDiagramDlgLayout.createSequentialGroup()
          .addContainerGap()
          .addGroup(NewDiagramDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewDiagramDlgLayout.createSequentialGroup()
              .addGap(0, 262, Short.MAX_VALUE)
              .addComponent(NewDiagCancelBtn)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(NewDiagOkBtn))
            .addGroup(NewDiagramDlgLayout.createSequentialGroup()
              .addComponent(DiagNameLabel)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(NewDiagNameText)))
          .addContainerGap())
      );
      NewDiagramDlgLayout.setVerticalGroup(
        NewDiagramDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewDiagramDlgLayout.createSequentialGroup()
          .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(NewDiagramDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(DiagNameLabel)
            .addComponent(NewDiagNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addGroup(NewDiagramDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(NewDiagOkBtn)
            .addComponent(NewDiagCancelBtn))
          .addContainerGap())
      );

      ConfirmDeleteDiagramDlg.setMinimumSize(new java.awt.Dimension(400, 200));
      ConfirmDeleteDiagramDlg.setModal(true);

      ConfDeleteDiagBtn.setText("Delete");
      ConfDeleteDiagBtn.addMouseListener(new java.awt.event.MouseAdapter()
      {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
          ConfDeleteDiagBtnMouseClicked(evt);
        }
      });

      ConfDeleteDiagCancelBtn.setText("Cancel");
      ConfDeleteDiagCancelBtn.addMouseListener(new java.awt.event.MouseAdapter()
      {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
          ConfDeleteDiagCancelBtnMouseClicked(evt);
        }
      });

      ConfirmDeleteDiagMsg.setText("ARE YOU SURE YOU WANT TO DELETE DIAGRAM?");

      javax.swing.GroupLayout ConfirmDeleteDiagramDlgLayout = new javax.swing.GroupLayout(ConfirmDeleteDiagramDlg.getContentPane());
      ConfirmDeleteDiagramDlg.getContentPane().setLayout(ConfirmDeleteDiagramDlgLayout);
      ConfirmDeleteDiagramDlgLayout.setHorizontalGroup(
        ConfirmDeleteDiagramDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(ConfirmDeleteDiagramDlgLayout.createSequentialGroup()
          .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(ConfDeleteDiagBtn)
          .addGap(46, 46, 46)
          .addComponent(ConfDeleteDiagCancelBtn)
          .addGap(131, 131, 131))
        .addGroup(ConfirmDeleteDiagramDlgLayout.createSequentialGroup()
          .addGap(70, 70, 70)
          .addComponent(ConfirmDeleteDiagMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGap(91, 91, 91))
      );
      ConfirmDeleteDiagramDlgLayout.setVerticalGroup(
        ConfirmDeleteDiagramDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConfirmDeleteDiagramDlgLayout.createSequentialGroup()
          .addContainerGap()
          .addComponent(ConfirmDeleteDiagMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addGroup(ConfirmDeleteDiagramDlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(ConfDeleteDiagCancelBtn)
            .addComponent(ConfDeleteDiagBtn))
          .addContainerGap())
      );

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      addWindowListener(new java.awt.event.WindowAdapter()
      {
        public void windowClosing(java.awt.event.WindowEvent evt)
        {
          formWindowClosing(evt);
        }
      });

      CreateProjectBtn.setText("Create Project");
      CreateProjectBtn.addMouseListener(new java.awt.event.MouseAdapter()
      {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
          CreateProjectBtnMouseClicked(evt);
        }
      });

      ExistingProjectsTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][]
        {

        },
        new String []
        {
          "Project", "Description"
        }
      )
      {
        Class[] types = new Class []
        {
          java.lang.String.class, java.lang.String.class
        };
        boolean[] canEdit = new boolean []
        {
          false, false
        };

        public Class getColumnClass(int columnIndex)
        {
          return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex)
        {
          return canEdit [columnIndex];
        }
      });
      ExistingProjectsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
      jScrollPane1.setViewportView(ExistingProjectsTable);
      if (ExistingProjectsTable.getColumnModel().getColumnCount() > 0)
      {
        ExistingProjectsTable.getColumnModel().getColumn(1).setHeaderValue("Description");
      }

      OpenProjectBtn.setText("Open Project");
      OpenProjectBtn.addMouseListener(new java.awt.event.MouseAdapter()
      {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
          OpenProjectBtnMouseClicked(evt);
        }
      });

      SelectWorkspaceBtn.setText("Select Workspace");
      SelectWorkspaceBtn.addMouseListener(new java.awt.event.MouseAdapter()
      {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
          SelectWorkspaceBtnMouseClicked(evt);
        }
      });

      DeleteProjectBtn.setText("Delete Project");
      DeleteProjectBtn.addMouseListener(new java.awt.event.MouseAdapter()
      {
        public void mouseClicked(java.awt.event.MouseEvent evt)
        {
          DeleteProjectBtnMouseClicked(evt);
        }
      });

      javax.swing.GroupLayout ProjectSelectDialogLayout = new javax.swing.GroupLayout(ProjectSelectDialog);
      ProjectSelectDialog.setLayout(ProjectSelectDialogLayout);
      ProjectSelectDialogLayout.setHorizontalGroup(
        ProjectSelectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(ProjectSelectDialogLayout.createSequentialGroup()
          .addContainerGap()
          .addGroup(ProjectSelectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProjectSelectDialogLayout.createSequentialGroup()
              .addGap(0, 0, Short.MAX_VALUE)
              .addComponent(DeleteProjectBtn)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(OpenProjectBtn))
            .addGroup(ProjectSelectDialogLayout.createSequentialGroup()
              .addGroup(ProjectSelectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CreateProjectBtn)
                .addComponent(SelectWorkspaceBtn))
              .addGap(0, 0, Short.MAX_VALUE)))
          .addContainerGap())
      );
      ProjectSelectDialogLayout.setVerticalGroup(
        ProjectSelectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(ProjectSelectDialogLayout.createSequentialGroup()
          .addComponent(SelectWorkspaceBtn)
          .addGap(17, 17, 17)
          .addComponent(CreateProjectBtn)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
          .addGroup(ProjectSelectDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(OpenProjectBtn)
            .addComponent(DeleteProjectBtn))
          .addContainerGap())
      );

      MainMenuFile.setText("File");

      MainMenuExit.setText("Exit");
      MainMenuExit.addActionListener(new java.awt.event.ActionListener()
      {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
          MainMenuExitActionPerformed(evt);
        }
      });
      MainMenuFile.add(MainMenuExit);

      MainMenuBar.add(MainMenuFile);

      setJMenuBar(MainMenuBar);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addContainerGap()
          .addComponent(ProjectSelectDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addContainerGap())
      );
      layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addContainerGap()
          .addComponent(ProjectSelectDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addContainerGap())
      );

      pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateProjectBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateProjectBtnMouseClicked
      NewProjectDlg.setVisible(true);
      updateProjectTable();
    }//GEN-LAST:event_CreateProjectBtnMouseClicked

    private void SelectWorkspaceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectWorkspaceBtnMouseClicked
      String path = config_mgr.getConfigValue(
              ConfigurationManager.WORKSPACE_PATH);
      File workspace = new File(path);
      WorkspaceChooser.setCurrentDirectory(workspace);
      int btnClicked = WorkspaceChooser.showOpenDialog(ged);
      if(btnClicked == JFileChooser.APPROVE_OPTION)
      {
        path = WorkspaceChooser.getSelectedFile().getAbsolutePath();
        project_mgr.switchWorkspace(path);
      }
      
      updateProjectTable();
    }//GEN-LAST:event_SelectWorkspaceBtnMouseClicked

  private void NewProjCancelBtnMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_NewProjCancelBtnMouseClicked
  {//GEN-HEADEREND:event_NewProjCancelBtnMouseClicked
    NewProjNameText.setText("");
    NewProjDescText.setText("");
    NewProjectDlg.setVisible(false);
  }//GEN-LAST:event_NewProjCancelBtnMouseClicked

  private void NewProjOkBtnMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_NewProjOkBtnMouseClicked
  {//GEN-HEADEREND:event_NewProjOkBtnMouseClicked
    NewProjectDlg.setVisible(false);
    String name = NewProjNameText.getText();
    String desc = NewProjDescText.getText();
    project_mgr.createProject(name, desc);
    NewProjNameText.setText("");
    NewProjDescText.setText("");
  }//GEN-LAST:event_NewProjOkBtnMouseClicked

  private void DeleteProjectBtnMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_DeleteProjectBtnMouseClicked
  {//GEN-HEADEREND:event_DeleteProjectBtnMouseClicked
    int rowNum = ExistingProjectsTable.getSelectedRow();
    if(rowNum >= 0)
    {
      String projName = (String) ExistingProjectsTable.getModel().getValueAt(
              rowNum, PROJECT_COLUMN);
      String confirmMessage = "<html>Are you sure you want to delete<br>" + 
              projName + "?</html>";
      ConfirmDeleteProjMsg.setText(confirmMessage);
      ConfirmDeleteProjMsg.setHorizontalAlignment(SwingConstants.CENTER);
      ConfirmDeleteProjectDlg.setVisible(true);
    }
  }//GEN-LAST:event_DeleteProjectBtnMouseClicked

  private void ConfDeleteProjBtnMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_ConfDeleteProjBtnMouseClicked
  {//GEN-HEADEREND:event_ConfDeleteProjBtnMouseClicked
    int rowNum = ExistingProjectsTable.getSelectedRow();
    if(rowNum >= 0)
    {
      String projName = (String) ExistingProjectsTable.getModel().getValueAt(
              rowNum, PROJECT_COLUMN);
      try
      {
        project_mgr.deleteProject(projName);
      }
      catch (IOException ex)
      {
        Logger.getLogger(GED_App.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
    ConfirmDeleteProjectDlg.setVisible(false);
    updateProjectTable();
  }//GEN-LAST:event_ConfDeleteProjBtnMouseClicked

  private void ConfDeleteProjCancelBtnMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_ConfDeleteProjCancelBtnMouseClicked
  {//GEN-HEADEREND:event_ConfDeleteProjCancelBtnMouseClicked
    ConfirmDeleteProjectDlg.setVisible(false);
  }//GEN-LAST:event_ConfDeleteProjCancelBtnMouseClicked

  private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
  {//GEN-HEADEREND:event_formWindowClosing
      exit();
  }//GEN-LAST:event_formWindowClosing

  private void OpenProjectBtnMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_OpenProjectBtnMouseClicked
  {//GEN-HEADEREND:event_OpenProjectBtnMouseClicked
    int rowNum = ExistingProjectsTable.getSelectedRow();
    if(rowNum >= 0)
    {
      String projName = (String) ExistingProjectsTable.getModel().getValueAt(
              rowNum, PROJECT_COLUMN);
      boolean opened = project_mgr.openProject(projName);
      if(opened)
      {
        ProjNameLabel.setText(projName);
        updateDiagramTable();
        DiagramSelectDialog.pack();
        ProjectSelectDialog.setVisible(false);
        DiagramSelectDialog.setVisible(true);
      }
    }
  }//GEN-LAST:event_OpenProjectBtnMouseClicked

  private void CreateDiagramBtnMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_CreateDiagramBtnMouseClicked
  {//GEN-HEADEREND:event_CreateDiagramBtnMouseClicked
    NewDiagramDlg.setVisible(true);
    updateDiagramTable();
  }//GEN-LAST:event_CreateDiagramBtnMouseClicked

  private void OpenDiagramBtnMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_OpenDiagramBtnMouseClicked
  {//GEN-HEADEREND:event_OpenDiagramBtnMouseClicked
    int rowNum = ExistingDiagramsTable.getSelectedRow();
    if(rowNum >= 0)
    {
      String diagName = (String) ExistingDiagramsTable.getModel().getValueAt(
              rowNum, 0);
      diagram_dlg.open(diagName);
    }
  }//GEN-LAST:event_OpenDiagramBtnMouseClicked

  private void DeleteDiagramBtnMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_DeleteDiagramBtnMouseClicked
  {//GEN-HEADEREND:event_DeleteDiagramBtnMouseClicked
    int rowNum = ExistingDiagramsTable.getSelectedRow();
    if(rowNum >= 0)
    {
      String diagName = (String) ExistingDiagramsTable.getModel().getValueAt(
              rowNum, 0);
      String confirmMessage = "<html>Are you sure you want to delete<br>" + 
              diagName + "?</html>";
      ConfirmDeleteDiagMsg.setText(confirmMessage);
      ConfirmDeleteDiagMsg.setHorizontalAlignment(SwingConstants.CENTER);
      ConfirmDeleteDiagramDlg.setVisible(true);
    }
  }//GEN-LAST:event_DeleteDiagramBtnMouseClicked

  private void CloseProjectBtnMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_CloseProjectBtnMouseClicked
  {//GEN-HEADEREND:event_CloseProjectBtnMouseClicked
    project_mgr.closeProject();
    DiagramSelectDialog.setVisible(false);
    ProjectSelectDialog.setVisible(true);
  }//GEN-LAST:event_CloseProjectBtnMouseClicked

  private void NewDiagOkBtnMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_NewDiagOkBtnMouseClicked
  {//GEN-HEADEREND:event_NewDiagOkBtnMouseClicked
    NewDiagramDlg.setVisible(false);
    try
    {
      String name = NewDiagNameText.getText();
      project_mgr.addDiagram(name);
    }
    catch (IOException ex)
    {
      Logger.getLogger(GED_App.class.getName()).log(Level.SEVERE, null, ex);
    }
    NewDiagNameText.setText("");
  }//GEN-LAST:event_NewDiagOkBtnMouseClicked

  private void NewDiagCancelBtnMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_NewDiagCancelBtnMouseClicked
  {//GEN-HEADEREND:event_NewDiagCancelBtnMouseClicked
    NewDiagNameText.setText("");
    NewDiagramDlg.setVisible(false);
  }//GEN-LAST:event_NewDiagCancelBtnMouseClicked

  private void ConfDeleteDiagBtnMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_ConfDeleteDiagBtnMouseClicked
  {//GEN-HEADEREND:event_ConfDeleteDiagBtnMouseClicked
    int rowNum = ExistingDiagramsTable.getSelectedRow();
    if(rowNum >= 0)
    {
      String diagName = (String) ExistingDiagramsTable.getModel().getValueAt(
              rowNum, 0);
      project_mgr.removeDiagram(diagName);
    }
    ConfirmDeleteDiagramDlg.setVisible(false);
    updateDiagramTable();
  }//GEN-LAST:event_ConfDeleteDiagBtnMouseClicked

  private void ConfDeleteDiagCancelBtnMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_ConfDeleteDiagCancelBtnMouseClicked
  {//GEN-HEADEREND:event_ConfDeleteDiagCancelBtnMouseClicked
    ConfirmDeleteDiagramDlg.setVisible(false);
  }//GEN-LAST:event_ConfDeleteDiagCancelBtnMouseClicked

  private void MainMenuExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MainMenuExitActionPerformed
  {//GEN-HEADEREND:event_MainMenuExitActionPerformed
    exit();
  }//GEN-LAST:event_MainMenuExitActionPerformed

  private void exit()
  {
    try
    {
      // Save config changes before closing
      ConfigurationManager cfgMgr;
      cfgMgr = ConfigurationManager.getInstance();
      cfgMgr.saveConfiguration();
    }
    catch (IOException ex)
    {
      Logger.getLogger(GED_App.class.getName()).log(Level.SEVERE, null, ex);
    }
    dispose();
    System.exit(0);
  }
  
  private void updateProjectTable()
  {
    // Get project table
    DefaultTableModel existingProjects = 
            (DefaultTableModel)ged.ExistingProjectsTable.getModel();
    project_mgr.updateProjectsTable(existingProjects);
  }
  
  private void updateDiagramTable()
  {
    // Get project table
    DefaultTableModel existingDiagrams = 
            (DefaultTableModel)ged.ExistingDiagramsTable.getModel();
    project_mgr.updateDiagramsTable(existingDiagrams);
  }
    
    /**
     * @param args the command line arguments
   * @throws java.io.IOException
     */
    public static void main(String args[]) throws IOException
    {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try 
      {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
        {
          if ("Nimbus".equals(info.getName()))
          {
            javax.swing.UIManager.setLookAndFeel(info.getClassName());
            break;
          }
        }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
          java.util.logging.Logger.getLogger(GED_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable()
      {
        @Override
        public void run()
        {
          try
          {
            ged = new GED_App();
            ged.updateProjectTable();
          }
          catch (IOException ex)
          {
            Logger.getLogger(GED_App.class.getName()).log(Level.SEVERE, null, ex);
          }
          ged.setVisible(true);
        }
      });
      
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton CloseProjectBtn;
  private javax.swing.JButton ConfDeleteDiagBtn;
  private javax.swing.JButton ConfDeleteDiagCancelBtn;
  private javax.swing.JButton ConfDeleteProjBtn;
  private javax.swing.JButton ConfDeleteProjCancelBtn;
  private javax.swing.JLabel ConfirmDeleteDiagMsg;
  private javax.swing.JDialog ConfirmDeleteDiagramDlg;
  private javax.swing.JLabel ConfirmDeleteProjMsg;
  private javax.swing.JDialog ConfirmDeleteProjectDlg;
  private javax.swing.JButton CreateDiagramBtn;
  private javax.swing.JButton CreateProjectBtn;
  private javax.swing.JButton DeleteDiagramBtn;
  private javax.swing.JButton DeleteProjectBtn;
  private javax.swing.JLabel DiagNameLabel;
  private javax.swing.JDialog DiagramSelectDialog;
  private javax.swing.JTable ExistingDiagramsTable;
  private javax.swing.JTable ExistingProjectsTable;
  private javax.swing.JMenuBar MainMenuBar;
  private javax.swing.JMenuItem MainMenuExit;
  private javax.swing.JMenu MainMenuFile;
  private javax.swing.JButton NewDiagCancelBtn;
  private javax.swing.JTextField NewDiagNameText;
  private javax.swing.JButton NewDiagOkBtn;
  private javax.swing.JDialog NewDiagramDlg;
  private javax.swing.JButton NewProjCancelBtn;
  private javax.swing.JTextField NewProjDescText;
  private javax.swing.JTextField NewProjNameText;
  private javax.swing.JButton NewProjOkBtn;
  private javax.swing.JDialog NewProjectDlg;
  private javax.swing.JButton OpenDiagramBtn;
  private javax.swing.JButton OpenProjectBtn;
  private javax.swing.JLabel ProjNameLabel;
  private javax.swing.JPanel ProjectSelectDialog;
  private javax.swing.JButton SelectWorkspaceBtn;
  private javax.swing.JFileChooser WorkspaceChooser;
  private javax.swing.JScrollPane dialogScrollPane;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
}
